### ISSUE TITLE
About Training Time.

### ISSUE THREAD

**Issue by RockeyCoss** [SalesforceAIResearch/DiffusionDPO#4]
Thank you for your amazing work! Does `Training takes ~24 hours / 2000 steps` refer to the training of sd1.5 or sdxl?

**Comment by wxbs** [comment]
Hey, how long does it take to train sdxl for 200 steps? Is it 30 hours? Your early reply would be highly appreciated. Thanks!

**Comment by SuperKenVery** [comment]
Hi, I wonder how fast it runs on your machines. I'm on 4xL20 and, as estimated by tqdm, it requires ~1month to run 2000 steps training SDXL.
