### ISSUE TITLE
I have some questions.

### ISSUE THREAD

**Issue by Mowenyii** [SalesforceAIResearch/DiffusionDPO#7]
Thank you for great work~

I want to know how this loss updates the model, because if epis_theta is initialized by epis_ref, the loss will be 0.
![image](https://github.com/SalesforceAIResearch/DiffusionDPO/assets/50766241/35b60bfa-78ec-4a6d-ad7e-8275ef632383)

**Comment by RockeyCoss** [comment]
Since log(sigmoid(0.0)) != 0, The loss will not 0 in the first step.

**Comment by yangluo23** [comment]
> Since log(sigmoid(0.0)) != 0, The loss will not 0 in the first step.

Yes, it is. This original loss function (DPO in LLM task) is designed well as there exists sampling in decoding step, enough though the intput and ref/target model is the same, the output would not the same yet. But for this diffusion settings, it is not. Even though the loss is non-zero, intuitively, it is wired.
